### ISSUE TITLE
Integrate Remote Config

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#48] opened 2021-03-04 09:41 UTC
Integrate Firebase engagement tool remote config

**Comment by DevilAJ** [comment] 2021-03-08 15:48
I would like to work on this issue.

**Comment by himanshusharma89** [comment] 2021-03-08 17:21
@DevilAJ 'll assign this to you as soon as the Firebase integration is merged.

**Comment by DevilAJ** [comment] 2021-03-09 08:12
Now I already have an issue assigned.
For now you can leave it open.
I will ask to assign as soon as I completed that issue.

**Comment by pawan2806** [comment] 2021-03-09 22:25
As the issue is still open , can you assign it to me @himanshusharma89 under Gssoc'21?

**Comment by himanshusharma89** [comment] 2021-03-10 04:13
Sure, we will rename the package and update the app on firebase. After this you can start working on it.

**Comment by pawan2806** [comment] 2021-03-23 06:53
What's the update on this @himanshusharma89 ?

**Comment by himanshusharma89** [comment] 2021-03-23 07:51
We can work on this now.

> What's the update on this @himanshusharma89 ?

**Closed** 2021-03-27 17:55 UTC
Labels: GSSOC21, Level2
