### ISSUE TITLE
Renderflex issue in the login & signup page

### ISSUE THREAD

**Issue by anotherwebguy** [himanshusharma89/relic_bazaar#186] opened 2021-04-10 05:36 UTC
# Bug Report 🐛
the login and signup page throws renderflex error when we go to enter our credentials

## Current Behavior
this should not happen in the app

## Possible Solution
Wrapping it with single Child scroll view would fix this issue

##Screenshots
![image](https://user-images.githubusercontent.com/66346161/114259597-b56bbb00-99ec-11eb-89ca-8c8498cd6f53.png)
![image](https://user-images.githubusercontent.com/66346161/114259600-b997d880-99ec-11eb-9a0e-5540147ace4b.png)

I would like to work on this issue under gssoc plz assign me this issue @himanshusharma89

**Comment by himanshusharma89** [comment] 2021-04-10 17:07
@anotherwebguy Why does the signup screen have a top bar? and what device are you using?

**Comment by anotherwebguy** [comment] 2021-04-10 17:15
> @anotherwebguy Why does the signup screen have a top bar? and what device are you using?


it was there when i runned the app
As u can see
The person who pushed signupview screen has used an appbar there
I would fix that too

And i am using android device
Redmi 4

**Comment by himanshusharma89** [comment] 2021-04-10 17:19
Just checked the code it was, I didn't add the background colour and elevation. Also, for small screen device, try to decrease the font size, spaces, icons and also the size of the whole stacked view. If the issue is still there use SingleChildScroll view (but for east possibility)
@anotherwebguy Fix the other PR and I'll assign this to you.

**Comment by anotherwebguy** [comment] 2021-04-11 01:42
> Just checked the code it was, I didn't add the background colour and elevation. Also, for small screen device, try to decrease the font size, spaces, icons and also the size of the whole stacked view. If the issue is still there use SingleChildScroll view (but for least possibility)
> @anotherwebguy Fix the other PR and I'll assign this to you.

Yes i'll do it

**Comment by anotherwebguy** [comment] 2021-04-12 13:28
Plz assign me this issue now @himanshusharma89

**Closed** 2021-04-17 09:04 UTC
Labels: GSSOC21, Level1, bug
