### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by himanshusharma89** [himanshusharma89/relic_bazaar#29] opened 2021-02-17 04:38 UTC

**Comment by Vansh-Gupta4** [comment] 2021-02-18 17:45
I would like to work on it

**Comment by himanshusharma89** [comment] 2021-02-18 18:09
Sure @Vansh-Gupta4, but are you participating in GSSOC? If so, it is better to contribute from March to gain the points.

**Comment by Vansh-Gupta4** [comment] 2021-02-18 19:16
Yes, I am participating in GSSOC..... but isn't this first come first serve
basis(please dont judge because i new to open source)

**Comment by ajay963** [comment] 2021-02-19 13:51
i am new to open source project and i have'nt participated in GSSOC  but i want to contribute to this project can i ??

**Comment by himanshusharma89** [comment] 2021-02-19 17:37
@Vansh-Gupta4 Yeah, but all contributions starts from March

**Comment by himanshusharma89** [comment] 2021-02-19 17:37
@ajay963 Sure, you can contribute to the project

**Comment by piyushpradhan** [comment] 2021-03-01 13:18
Can I work on this ? I'd really like to contribute to this project.

**Comment by himanshusharma89** [comment] 2021-03-01 13:34
Sure, @piyushpradhan, you can contribute to this project. And if you are participating in GSSOC, you can read the above comments.

**Comment by piyushpradhan** [comment] 2021-03-01 14:14
Yes, I am participating in GSSOC. Thank you.

**Comment by himanshusharma89** [comment] 2021-03-08 04:43
@Vansh-Gupta4 assigning it to you as you commented on it earlier. And @piyushpradhan, you can comment on any other issue.

**Comment by Vansh-Gupta4** [comment] 2021-03-08 12:44
Thanks alot

**Comment by Vansh-Gupta4** [comment] 2021-03-08 12:48
i have to write "about page"...right?

**Comment by himanshusharma89** [comment] 2021-03-08 12:55
@Vansh-Gupta4 You need to create an About Page, for reference you can check out other apps containing about page ut make sure to create it in a retro theme.

**Comment by Vansh-Gupta4** [comment] 2021-03-08 13:04
where i can check other apps containing about page

**Comment by himanshusharma89** [comment] 2021-03-08 13:07
@Vansh-Gupta4 You can refer to this:
![image](https://user-images.githubusercontent.com/44980497/110325350-3b3ac600-803d-11eb-9000-6da143144645.png)

**Comment by Vansh-Gupta4** [comment] 2021-03-08 13:10
thanks @himanshusharma89 i have to make it using html and css ..right?

**Comment by himanshusharma89** [comment] 2021-03-08 13:13
No @Vansh-Gupta4, this is a Flutter based project.

**Comment by Vansh-Gupta4** [comment] 2021-03-08 13:14
but i dont know flutter

**Comment by himanshusharma89** [comment] 2021-03-08 13:15
You should have checked it earlier before commenting, but no issues you can contribute to other projects who have the web tech stack.

**Comment by Vansh-Gupta4** [comment] 2021-03-08 13:16
ohkk..thankyou  @himanshusharma89

**Comment by piyushpradhan** [comment] 2021-03-08 19:22
If @Vansh-Gupta4 isn't going to work on this issue, can I be assigned this issue ?

**Comment by himanshusharma89** [comment] 2021-03-08 19:24
@piyushpradhan one person can work on one issue at a-time, so that everyone can contribute to the project.

**Comment by piyushpradhan** [comment] 2021-03-08 19:44
Ohh okay, got it!

**Comment by pratikbaid3** [comment] 2021-03-09 06:24
@himanshusharma89 if no one is working on this, I'd like to work on it.

**Comment by himanshusharma89** [comment] 2021-03-09 07:19
Hey @pratikbaid3, are you participating in GSSOC?

**Comment by pratikbaid3** [comment] 2021-03-09 07:24
Yes I am @himanshusharma89

**Comment by D-Ajay-Kumar** [comment] 2021-03-11 08:39
If the issue is still open I can work on it.

**Comment by pratikbaid3** [comment] 2021-03-11 08:50
@D-Ajay-Kumar I am currently working on this and will create a PR soon

**Comment by D-Ajay-Kumar** [comment] 2021-03-11 08:54
All the best man

**Comment by himanshusharma89** [comment] 2021-03-14 06:11
@pratikbaid3 Is this issue resolved?

**Comment by pratikbaid3** [comment] 2021-03-14 06:14
@himanshusharma89 I am currently working on #69 as that is a prerequisite, I'll be finishing that in some time and then do this.

**Comment by pratikbaid3** [comment] 2021-03-14 11:40
@himanshusharma89 #69 is taking some time. If someone else is willing to work on this issue, you can assign them. I'll first have to fix #69 anyways before I can start with this.

**Comment by himanshusharma89** [comment] 2021-03-14 11:44
@pratikbaid3 Okay, I'll assign it to someone else, if he/she commented before that issue is resolved.

**Comment by D-Ajay-Kumar** [comment] 2021-03-14 12:06
Can do it

**Comment by D-Ajay-Kumar** [comment] 2021-03-14 12:37
On it

**Comment by D-Ajay-Kumar** [comment] 2021-03-14 15:50
How do these look?

![WhatsApp Image 2021-03-14 at 9 16 47 PM](https://user-images.githubusercontent.com/56850266/111074847-07fba980-850b-11eb-96c2-60bbf4b8231b.jpeg)
![WhatsApp Image 2021-03-14 at 9 17 02 PM](https://user-images.githubusercontent.com/56850266/111074849-0e8a2100-850b-11eb-9126-ba2e5b36ef5d.jpeg)

**Comment by himanshusharma89** [comment] 2021-03-14 16:07
@D-Ajay-Kumar Looks good, create a PR. I hope you are following all the lining rules and making sure that you commit to finalise your work.

**Comment by D-Ajay-Kumar** [comment] 2021-03-14 16:16
Done. Please check the code :)

**Closed** 2021-03-14 16:21 UTC
Labels: GSSOC21, Level1
