### ISSUE TITLE
Pod install error on M1 using iPhone 12 Pro max simulator

### ISSUE THREAD

**Issue by nakshatrasinghh** [himanshusharma89/relic_bazaar#69] opened 2021-03-09 06:10 UTC
Any quick fixes to kick off the application on this simulator? 

<img width="1440" alt="Screenshot 2021-03-09 at 11 39 04 AM" src="https://user-images.githubusercontent.com/53419293/110426413-104b8300-80cc-11eb-826e-c82569f28e15.png">

**Comment by himanshusharma89** [comment] 2021-03-09 07:17
Hey @nakshatrasinghh, I don't own a macOS device, but can you share the error message? and if you want to resolve this issue, I can assign it to you(If you are participating in GSSOC).

**Comment by pratikbaid3** [comment] 2021-03-09 07:23
@himanshusharma89 
```[!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
  In Podfile:
    razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)

Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.``` 
The issue is with cocoapods compatibility with razor pay.

I'd like to work on fixing this

**Comment by nakshatrasinghh** [comment] 2021-03-09 07:28
> Hey @nakshatrasinghh, I don't own a macOS device so couldn't test it. But can you share the error message? and if you want to resolve this issue, I can assign it to you(If you are participating in GSSOC).

I'll like to work on this issue, it has something to do with razor pay and cocoapods. Will solve this issue soon. Yes I'm a participant in GSSoC' 21

**Comment by himanshusharma89** [comment] 2021-03-09 07:30
I found this: https://github.com/dynamitechetan/razorpay_flutter/issues/16 which will eventually lead you to this: https://github.com/dynamitechetan/razorpay_flutter/issues/19#issuecomment-495486681

**Comment by himanshusharma89** [comment] 2021-03-09 07:31
Also, I think @nakshatrasinghh, should work on this as he created this issue. But @pratikbaid3 if you are participating in GSSOC you can create an issue of Firebase Integration and help out with Apple Auth?

**Comment by pratikbaid3** [comment] 2021-03-12 11:02
@nakshatrasinghh Any chance this is fixed?

**Comment by himanshusharma89** [comment] 2021-03-12 11:20
Yeah @nakshatrasinghh, do let me know the updates on the issue.

**Comment by nakshatrasinghh** [comment] 2021-03-12 17:18
> Yeah @nakshatrasinghh, do let me know the updates on the issue.

Sorry for the late response @himanshusharma89, no I tried several things to solve it, but nothing seems to work as of now :(

**Comment by himanshusharma89** [comment] 2021-03-12 17:43
> > Yeah @nakshatrasinghh, do let me know the updates on the issue.
> 
> Sorry for the late response @himanshusharma89, no I tried several things to solve it, but nothing seems to work as of now :(

I don't know much of this issue @pratikbaid3 can you help him out via Discord?

**Comment by nakshatrasinghh** [comment] 2021-03-12 17:48
> > > Yeah @nakshatrasinghh, do let me know the updates on the issue.
> > 
> > 
> > Sorry for the late response @himanshusharma89, no I tried several things to solve it, but nothing seems to work as of now :(
> 
> I don't know much of this issue @pratikbaid3 can you help him out via Discord?

Yes @pratikbaid3 we can connect on discord and work the issue

**Comment by pratikbaid3** [comment] 2021-03-12 18:54
@himanshusharma89 Ya sure. I'll look into this issue and get in touch with @nakshatrasinghh.

**Comment by himanshusharma89** [comment] 2021-03-23 10:05
Any update on this? @pratikbaid3 @nakshatrasinghh

**Closed** 2021-05-05 18:06 UTC
Labels: GSSOC21, Level2, bug
